# Site settings
title: Picnic15
email: your-email@domain.com
description: Comem29 alumni picnic
baseurl: "/picnic15" # the subpath of your site, e.g. /blog/
url: "https://comem29.github.io" # the base hostname & protocol for your site
exclude: [bower_components,node_modules]
permalink: /:year/:month/:day/:title

# Build settings
markdown: kramdown
